In [1]:
import numpy as np

In [2]:
a = [1,2,3,4]
print(type(a))

<class 'list'>


In [27]:
b = np.array(a)
print(b)
print(b.max())
print(b.min())
print(type(b))

[1 2 3 4]
4
1
<class 'numpy.ndarray'>


In [4]:
b.ndim

1

In [15]:
c = [[[1,2],[2,3]],[[1,2],[3,4]]]
d = np.array(c)
print(d.ndim)
print(d.shape)
print(d.dtype)
print(type(d))
d.size

3
(2, 2, 2)
int32
<class 'numpy.ndarray'>


8

In [13]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
ones = np.ones((6,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.random.random((3,3))

array([[0.88226571, 0.7164535 , 0.42402688],
       [0.34054999, 0.14071432, 0.88346284],
       [0.84301549, 0.86721684, 0.84107786]])

In [17]:
np.random.random()

0.7343054885982284

In [18]:
np.arange(1,10,1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
ones = np.reshape(ones,(2,9))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
ones.flatten()

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1.])

In [23]:
ones + 1

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [24]:
ones / 2

array([[0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]])

In [25]:
ones = ones + 2
ones

array([[3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [26]:
ones - 1

array([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.max()

9

In [30]:
arr.min()

1

In [31]:
arr.max(axis=0)

array([7, 8, 9])

In [32]:
arr.max(axis=1)

array([3, 6, 9])

In [33]:
arr.sum()

45

In [34]:
arr1 = np.array([[1,2,3],
               [4,5,6],
               [7,8,9]])

arr2 = np.array([[9,8,7],
               [6,5,4],
               [3,2,1]])

arr3 = np.array([[9,8,7,5],
               [6,5,4,2],
               [3,2,1,5]])

In [35]:
arr1.dot(arr2)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [37]:
arr2.sort()
arr2

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [38]:
np.sort(arr2 ,axis=1 ,kind='mergesort')

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [39]:
np.sort(arr2 ,axis=0 ,kind='mergesort')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
np.vstack((arr1,arr2))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [42]:
np.hstack((arr1,arr2))

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [43]:
np.concatenate((arr1,arr2),axis=1)

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 1, 2, 3]])

In [45]:
arr = np.concatenate((arr1,arr2),axis=0)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [46]:
np.hsplit(arr,3)

[array([[1],
        [4],
        [7],
        [7],
        [4],
        [1]]),
 array([[2],
        [5],
        [8],
        [8],
        [5],
        [2]]),
 array([[3],
        [6],
        [9],
        [9],
        [6],
        [3]])]

In [47]:
np.vsplit(arr,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])]

In [48]:
lst = np.array([1,2,3,4,5,6,7,8,9])
lst>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [49]:
lst[lst>5]

array([6, 7, 8, 9])